export const phraseMap: Record<string, string> = {
	flirt: 'rizz up',
	flirted: 'rizzed up',
	flirting: 'rizzing up',
	'big butt': 'level 100 gyatt',
	workout: 'looksmax',
	'working out': 'looksmaxxing',
	'work out': 'looksmax',
	'worked out': 'looksmaxxed',
	bodybuilder: 'looksmaxxer',
	'body builder': 'looksmaxxer',
	steal: 'fanum tax',
	take: 'fanum tax',
	rob: 'fanum tax',
	borrow: 'fanum tax',
	stole: 'fanum taxxed',
	took: 'fanum taxxed',
	robbed: 'fanum taxxed',
	// borrow: 'fanum taxxed',
	stolen: 'fanum taxxed',
	stealing: 'fanum taxxing',
	taking: 'fanum taxxing',
	robbing: 'fanum taxxing',
	borrowing: 'fanum taxxing',
	weird: 'made in Ohio',
	strange: 'made in Ohio',
	unusual: 'made in Ohio',
	crazy: 'made in Ohio',
	'be quiet': "they're mewing",
	'do good': 'eat',
	'did good': 'ate',
	'doing good': 'eating',
	'do great': 'eat and leave no crumbs',
	'did great': 'ate and left no crumbs',
	'doing great': 'eating and leaving no crumbs'
};

export const wordMap: Record<string, string> = {
	charisma: 'rizz',
	style: 'rizz',
	charm: 'rizz',
	attractive: 'rizzy',
	hot: 'rizzy',
	cute: 'rizzy',
	pretty: 'rizzy',
	handsome: 'rizzy',
	butt: 'gyatt',
	ass: 'gyatt',
	hell: 'Ohio',
	good: 'goated',
	delicious: "bussin'",
	great: "bussin'",
	better: 'goated',
	best: 'goat',
	vibe: 'aura',
	lying: 'capping',
	lieing: 'capping',
	lie: 'cap',
	lied: 'capped',
	liar: 'capper',
	liars: 'cappers',
	wild: 'skibidi',
	evil: 'skibidi',
	stupid: 'skibidi',
	silly: 'skibidi',
	dastardly: 'skibidi',
	amazing: 'level 100',
	loss: 'L',
	loser: 'L person',
	win: 'W',
	winner: 'W person',
	big: 'huge',
	yes: 'bet',
	agreed: 'bet',
	agree: 'bet',
	tune: 'bop',
	music: 'bop',
	song: 'bop',
	old: 'cheugy',
	uncool: 'cheugy',
	outdated: 'cheugy',
	delusional: 'delulu',
	insane: 'delulu',
	crazy: 'delulu',
	dumb: 'delulu',
	gross: 'cringe',
	lame: 'cringe',
	awesome: 'based',
	// true: 'based',
	toilet: 'skibidi',
	im: 'literally',
	"i'm": 'literally',
	facts: 'fax',
	factual: 'fax',
	true: 'fax',
	truth: 'fax',
	gonna: 'finna',
	'going to': 'finna',
	'about to': 'finna',
	'fixing to': 'finna',
	leave: 'head out',
	jam: 'bop',
	change: 'glow up',
	transformation: 'glow up',
	transform: 'glow up',
	ignore: 'ghost',
	ignored: 'ghosted',
	ignoring: 'ghosting',
	cool: 'goated',
	disgust: 'ick',
	seems: 'is giving',
	'a little': 'lowkey',
	'little bit': 'lowkey'
};

export const randomWordList: string[] = [
	'skibidi',
	'toilet',
	'gyatt',
	'rizz',
	'only in ohio',
	'duke dennis',
	'pray today',
	'livvy dunne',
	'rizzing up',
	'baby gronk',
	'sussy',
	'imposter',
	'pibby glitch',
	'in real life',
	'sigma',
	'alpha',
	'omega male',
	'grindset',
	'andrew tate',
	'freddy fazbear',
	'colleen ballinger',
	'smurf cat',
	'strawberry elephant',
	'blud',
	'dawg',
	'shmlawg',
	'ishowspeed',
	'bro really thinks',
	'carti',
	'literally',
	'hitting the griddy',
	'griddy',
	'hit the griddy',
	'ocky way',
	'kai cenat',
	'fanum tax',
	'garten of banban',
	'edging',
	'bussing',
	'whopper whopper whopper',
	'1 2 buckle my shoe',
	'goofy ahh',
	'ahh',
	'adin ross',
	'sin city',
	'monday left me broken',
	'quirked up',
	'busting it down',
	'goated with the sauce',
	'goated',
	'goat',
	'john pork',
	'grimace shake',
	'huggy wuggy',
	'nathaniel b',
	'biggest bird',
	'amogus',
	'uncanny',
	'wholesome',
	'reddit',
	'chungus',
	'keanu reeves',
	'pizza tower',
	'zesty',
	'poggers',
	'kumalala savesta',
	'quandale dingle',
	'glizzy',
	'thug shaker',
	'shaker',
	'morbin time',
	'dj khaled',
	'sisyphus',
	'shadow wizard money gang',
	'ayo the pizza here',
	'plug',
	'nair',
	'compilation',
	'subway surfers',
	'funny moments',
	'nickeh30',
	'ratio',
	'delulu',
	'opium bird',
	'mewing',
	'mew',
	'looksmax',
	'looksmaxxing',
	'fortnite',
	'battle pass',
	'all my fellas',
	'gta 6',
	'backrooms',
	'gigachad',
	'based',
	'cringe',
	'redpilled',
	'F in the chat',
	'lean',
	'looksmaxxing',
	'gassy',
	'xbox live',
	'mrbeast',
	'kid named finger',
	'better caul saul',
	'i am a surgeon',
	'ya cut g',
	'ice spice',
	'gooning',
	'fr',
	'we go gym',
	'josh hutcherson',
	'metal pipe falling',
	'level 600 gyatt',
	'gyatt',
	'rizzler',
	'ohio',
	'rizzonomics',
	'sturdy',
	'kai cenat',
	'fanum',
	'fanum tax',
	'griddying',
	'bomboclat',
	'rizzard of oz',
	'rizz king',
	'sussy baka',
	'erm',
	'what the sigma',
	'sigma',
	'infinite rizz',
	'negative rizz',
	'barbenheimer',
	'sbidi toiledt',
	'roblox',
	'therian',
	'baby gronk',
	"dog doin'",
	'we go jim',
	'zyzz',
	'cuh dey board',
	'L rizz',
	'W rizz',
	'L streamer',
	'W streamer',
	'L',
	'W',
	'girl dinner',
	'boy dinner',
	'girl math',
	'poppy playtime',
	"bussin'",
	'zoomer',
	'ipad kid',
	'cocomelon',
	'chat',
	'tiktok',
	'rizz party',
	'nonchalant',
	'glazing',
	'glazer',
	'brainrot'
];

export const everyBrainrot: string[] = Array.from(
	new Set([...Object.values(phraseMap), ...Object.values(wordMap), ...randomWordList])
);
