export const bootMessages: string[] = [
	'Starting system log daemon...',
	'Initializing hardware...',
	'Mounting root filesystem...',
	'Loading initial ramdisk...',
	'Detected CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz',
	'Checking battery status...',
	'Starting udev Kernel Device Manager...',
	'Configuring network interfaces...',
	'Starting DHCP client daemon...',
	'Starting OpenSSH server...',
	'Reached target Basic System.',
	'Starting Login Service...',
	'Started Network Manager.',
	'Starting D-Bus System Message Bus...',
	'Mounting temporary filesystems...',
	'Starting Avahi mDNS/DNS-SD Stack...',
	'Checking filesystems...',
	'Started Disk Manager.',
	'Mounting /home...',
	'Starting ACPI event daemon...',
	'Enabling swap space...',
	'Started system logging service.',
	'Reached target System Initialization.',
	'Starting GNOME Display Manager...',
	'Reached target Multi-User System.',
	'Reached target Graphical Interface.',
	'Started Authorization Manager.',
	'Starting firewall service...',
	'Starting Bluetooth Service...',
	'Starting CUPS Scheduler...',
	'Started Command Scheduler (cron).',
	'Starting Apache HTTP Server...',
	'Starting MySQL Database Server...',
	'Reached target Network is Online.',
	'Reached target Sound Card.',
	'Starting X Display Manager...',
	'Started Virtual Console Logging Service.',
	'Starting Cleanup of Temporary Directories...',
	'Starting Dynamic Kernel Modules...',
	'Welcome to Linux!'
];
