import type { Sound } from './types';

export const bootMessages: string[] = [
	'Starting system log daemon...',
	'Initializing hardware...',
	'Mounting root filesystem...',
	'Loading initial ramdisk...',
	'Detected CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz',
	'Checking battery status...',
	'Starting udev Kernel Device Manager...',
	'Configuring network interfaces...',
	'Starting DHCP client daemon...',
	'Starting OpenSSH server...',
	'Reached target Basic System.',
	'Starting Login Service...',
	'Started Network Manager.',
	'Starting D-Bus System Message Bus...',
	'Mounting temporary filesystems...',
	'Starting Avahi mDNS/DNS-SD Stack...',
	'Checking filesystems...',
	'Started Disk Manager.',
	'Mounting /home...',
	'Starting ACPI event daemon...',
	'Enabling swap space...',
	'Started system logging service.',
	'Reached target System Initialization.',
	'Starting GNOME Display Manager...',
	'Reached target Multi-User System.',
	'Reached target Graphical Interface.',
	'Started Authorization Manager.',
	'Starting firewall service...',
	'Starting Bluetooth Service...',
	'Starting CUPS Scheduler...',
	'Started Command Scheduler (cron).',
	'Starting Apache HTTP Server...',
	'Starting MySQL Database Server...',
	'Reached target Network is Online.',
	'Reached target Sound Card.',
	'Starting X Display Manager...',
	'Started Virtual Console Logging Service.',
	'Starting Cleanup of Temporary Directories...',
	'Starting Dynamic Kernel Modules...',
	'Welcome to Linux!'
];

export const sounds: Sound[] = [
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/invincible.mp3',
		name: 'Deaf Kev - Invincible',
		delay: 10.79
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/hellcat.mp3',
		name: 'Desmeon - Hellcat',
		delay: 11.83
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/myheart.mp3',
		name: 'Different Heaven & EH!DE - My Heart',
		delay: 11.03
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/skyhigh.mp3',
		name: 'Elektronomia - Sky High',
		delay: 9.37
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/blank.mp3',
		name: 'Disfigure - Blank',
		delay: 13.71
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/nekozilla.mp3',
		name: 'Different Heaven - Nekozilla',
		delay: 9.4
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/firefly.mp3',
		name: 'Jim Yosef - Firefly',
		delay: 14.77
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/high.mp3',
		name: 'JPB - High',
		delay: 12.79
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/linked.mp3',
		name: 'Jim Yosef & Anna Yvette - Linked',
		delay: 19.19
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/popsicle.mp3',
		name: 'LFZ - Popsicle',
		delay: 15.0
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/eclipse.mp3',
		name: 'Jim Yosef - Eclipse',
		delay: 15.36
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/savage.mp3',
		name: 'Paul Flint - Savage',
		delay: 12.79
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/onandon.mp3',
		name: 'Cartoon, Jéja - On & On',
		delay: 22.55
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/mortals.mp3',
		name: 'Warriyo - Mortals (feat. Laura Brehm)',
		delay: 16.04
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/whywelose.mp3',
		name: 'Cartoon, Jéja - Why We Lose (feat. Coleman Trapp)',
		delay: 10.33
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/symbolism.mp3',
		name: 'Electro-Light - Symbolism',
		delay: 11.29
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/shine.mp3',
		name: 'Spektrem - Shine',
		delay: 20.19
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/invisible.mp3',
		name: 'Julius Dreisig & Zeus X Crona - Invisible',
		delay: 11.66
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/feelgood.mp3',
		name: 'Syn Cole - Feel Good',
		delay: 15.48
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/energy.mp3',
		name: 'Elektronomia - Energy',
		delay: 15.0
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/heroestonight.mp3',
		name: 'Janji - Heroes Tonight',
		delay: 14.56
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/stronger.mp3',
		name: 'Prismo - Stronger',
		delay: 14.19
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/puzzle.mp3',
		name: 'RetroVision - Puzzle',
		delay: 14.99
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/fearless.mp3',
		name: 'Lost Sky - Fearless',
		delay: 8.72
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/cetus.mp3',
		name: 'Lensko - Cetus',
		delay: 16.87
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/zigzag.mp3',
		name: 'Clarx - Zig Zag',
		delay: 15.0
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/arrow.mp3',
		name: 'Jim Yosef - Arrow',
		delay: 14.77
	},
	{
		src: 'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/music/jumbo.mp3',
		name: 'Alex Skrindo - Jumbo',
		delay: 16.61
	}
];

export const images: string[] = [
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cantaloupe.jpg',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/acorn.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/apple.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/avocado.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bananas.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/blackberries.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/blueberries.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cherry.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/coconut.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/dragonfruit.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/durian.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/grapesgreen.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/grapespurple.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/grapesred.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/honeydew.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/kiwi.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/kiwibird.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lemon.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/mango.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/mangosteen.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/orange.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/annoyingorange.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/papaya.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/peach.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pear.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pineapple.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/plum.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pomegranate.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/raspberries.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/strawberry.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tomato.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/watermelon.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/asparagus.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/beet.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bellpeppergreen.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bellpepperorange.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bellpepper.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bellpepper.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/carrot.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cauliflower.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/celery.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/corn.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cucumber.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/eggplant.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/garlic.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/jackolantern.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/jalapeno.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lettuce.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/mushroom.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/onion.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pumpkin.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/squash.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/turnips.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/peas.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/potato.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/burger.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cake.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/cheese.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/chickennugget.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/donuts.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/dough.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/egg.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/fries.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/gelatin.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/hotdog.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/icecream.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/icecube.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lemonade.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lollipop.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/marshmallow.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/oj.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pickles.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pie.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pizza.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pumpkinpie.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/rice.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tacos.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/teacup.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/water.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bottle.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tissues.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/candle.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/chair.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/clock.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/fan.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/gate.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lightswitch.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pillow.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/plate.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/soap.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/soapbar.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/sponge.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/table.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/toilet.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/toiletpaper.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/fork.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/knife.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pepper.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/salt.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/spoon.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/spork.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/teakettle.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/paper.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pencil.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/eraser.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pencilsharpener.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/ruler.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/calc.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/scissors.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pen.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/marker.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/stapler.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/filecabinet.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/hammer.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lawnmower.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/nails.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/saw.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/computer.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/microphone.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/phone.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/remote.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/speakers.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tv.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/8ball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/block.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/football.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/soccerball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/golfball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tennisball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tennisracket.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/basketball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/baseball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/clover.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/leaf.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/rock.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/therock.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/tree.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/checkbook.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/dime.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/dollar.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/nickel.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/coin.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/quarter.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/wallet.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/balloon.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/barrel.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bell.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/book.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bow.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/box.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bracelet.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/brick.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/bubble.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lifering.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lightbulb.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/match.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/needle.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/paintbrush.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/paperbag.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pushpin.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/pricetag.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/ruby.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/smallglassjar.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/snowball.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/stopwatch.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/suitcase.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/testtubes.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/trophy.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/yinyang.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/websim.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/sean.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/lemur.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/grumpycatkeychain.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/rat.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/yahamouse.png',
	'https://file.garden/ZxmC4yQL6hzekzvV/ncsobjects/images/loss.png'
];
