name: Refresh ReVanced Manager data
on:
    schedule:
        - cron: '* * * * *'
jobs:
    refresh-feed:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Fetch API Data 📦
              uses: JamesIves/fetch-api-data-action@v2.3.0
              with:
                  endpoint: https://api.revanced.app/v2/patches/latest
                  retry: true
            - name: Build and Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  token: ${{ secrets.ACCESS_TOKEN }}
                  branch: master # Pushes the updates to the master branch.
                  folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
                  target-folder: data # Saves the data into the 'data' directory on the master branch.
